blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name


urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view_blog'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='название блога')
    slug = models.CharField(max_length=200, **NULLABLE, verbose_name='slug')
    content = models.TextField(**NULLABLE, verbose_name='содержимое блога')
    image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='изображение')
    date_created = models.DateField(**NULLABLE, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликован')
    view_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from blog.models import Blog
from pytils.translit import slugify


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'slug', 'is_published', 'view_count',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):  # Задание 3: выводить в список статей только те, которые имеют положительный признак публикации
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)  # В консоли нужно установить модуль pytils
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):    # Задание 3: при открытии отдельной статьи увеличивать счетчик просмотров;
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'slug', 'is_published', 'view_count',)

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save()
            blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.object.slug])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                  <p>Вы уверенны?</p>
                    <button type="submit" class="btn btn-secondary">Удалить</button>
                  <a href="{% url 'blog:list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="col">
    <a href="{% url 'blog:list' %}" type="button"
                       class="btn btn-secondary">вернуться</a>

    <div class="card shadow-sm">

        <div class="text-center">
            <img src="/media/{{ object.preview }}" width="500" height="250" class="rounded" alt="Card image cap">
        </div>

        <p class="text-center fw-bold">
            {{ object.title }}
        </p>

        <div class="card-body">
            <p class="text-center">{{ object.content }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blog:edit_blog' object.pk %}" type="button"
                       class="btn btn-secondary">редактирование</a>
                    <a href="{% url 'blog:delete_blog' object.pk %}" type="button"
                       class="btn btn-secondary">удаление</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-secondary">
                        {% if object %}
                        сохранить
                        {% else %}
                        создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="album py-4 bg-body-tertiary text-center">
    <h1>Blog</h1>
    <div class="container">
        <div class="row">
            <div class="col-12 mb-5">
                <a href="{% url 'blog:create' %}" type="button" class="btn btn-secondary">Добавить блог</a>
            </div>
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="text-center">
                        <img src="/media/{{ object.image }}" class="rounded" alt="preview" width="100%" height="100">
                    </div>
                    <p class="text-center fw-bold">
                        {{ object.title | title }}
                    </p>
                    <div class="card-body">
                        <p class="text-center">{{ object.content }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'blog:view_blog' object.pk %}" type="button"
                                   class="btn btn-secondary">просмотр</a>
                                <a href="{% url 'blog:edit_blog' object.pk %}" type="button"
                                   class="btn btn-secondary">редактирование</a>
                                <a href="{% url 'blog:delete_blog' object.pk %}" type="button"
                                   class="btn btn-secondary">удаление</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endblock %}