blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name


urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view_blog'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete_blog'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import (ProductListView, ProductDetailView, CategoryListView, CategoryProductListView,
                           ProductCreateView, ProductUpdateView, ProductDeleteView, VersionCreateView)
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('product_list', ProductListView.as_view(), name='list'),
    path('product_list/<int:pk>/', CategoryProductListView.as_view(), name='product_list'),
    path('detail_list/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='detail_list'),
    path('', CategoryListView.as_view(), name='category_list'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('versions/create/', VersionCreateView.as_view(), name='create_version'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, generate_new_password, activate_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    # path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    # path('verify_email/<str:uid>/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
    path('verify/', activate_user, name='верификация'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='категория продукта')
    description = models.TextField(**NULLABLE, verbose_name='описание категории')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование продукта')
    description = models.TextField(verbose_name='описание продукта')
    image = models.ImageField(upload_to='product_image/', **NULLABLE, verbose_name='изображение продукта')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория продукта')
    price = models.FloatField(verbose_name='стоимость за единицу')
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True, verbose_name='опубликован')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='продавец')

    def __str__(self):
        return f"{self.name} по цене: {self.price}"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

        permissions = [
            ('set_is_published', 'разрешено менять публикацию товаров')
            # ('set_description', 'разрешено менять описание товаров'),
            # ('set_category', 'разрешено менять категорию товаров'),
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    is_active = models.BooleanField(default=False, verbose_name='активность версии')

    def __str__(self):
        return f'{self.product} - {self.version_number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.core.exceptions import PermissionDenied

from catalog.models import Product, Version


class UserPassesTestMixin:
    def dispatch(self, request, *args, **kwargs):
        if not self.test_func(request.user):
            # Действия, если пользователь не проходит проверку
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def test_func(self, user):
        # Реализуйте свою логику проверки здесь
        # В этом примере, пользователь должен быть модератором или владельцем
        return user.is_authenticated and (user.is_moderator or self.is_owner(user))

    def is_owner(self, user):
        # Реализуйте свою логику проверки владельца здесь
        # Здесь предполагается, что у модели есть поле "owner", содержащее владельца
        return user == self.get_object().owner


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('owner',)
        # fields = ('name', 'description', 'image', 'category', 'price', 'is')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        banned_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in banned_words:
            if word in cleaned_data:
                raise forms.ValidationError('Такие слова нельзя использовать в названии продукта')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        banned_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in banned_words:
            if word in cleaned_data:
                raise forms.ValidationError('Такие слова нельзя использовать в названии продукта')
        return cleaned_data


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        # fields = ('product', 'version_number', 'version_name', 'is_active',)
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.http import Http404, HttpResponse
from django.urls import reverse_lazy
from django.views import View

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Category, Version
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.services import get_cached_categories


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_versions = Version.objects.filter(is_active=True)
        if active_versions:
            context['active_versions'] = active_versions
        else:
            context['active_versions'] = None
        return context


class ProductDetailView(DetailView):
    model = Product


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_cached_categories()
        return context_data


class CategoryProductListView(ListView):
    model = Category

    def get_queryset(self):
        category_pk = self.kwargs['pk']
        return Product.objects.filter(category_id=category_pk)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')
    # permission_required = 'catalog.add_product'


    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(UpdateView, PermissionRequiredMixin):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')
    permission_required = 'catalog.change_product'


    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Product.objects.all()
        if not self.request.user.is_staff:
            context_data['object_list'] = Product.objects.filter(is_published=True)
        return context_data


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:list')
    permission_required = 'catalog.delete_product'

    def test_func(self):
        return self.request.user.is_superuser


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:list')


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Магазин продуктов</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4>Меню</h4>
                    <a href="{% url 'catalog:list' %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Продукты</a>
                    <a href="{% url 'blog:list' %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Блог</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:profile' %}" type="button" class="btn btn-sm btn-outline-secondary">Профиль</a>
                    <a href="{% url 'users:logout' %}" type="button" class="btn btn-sm btn-outline-secondary">Выход</a>
                    {% else %}
                    <a href="{% url 'users:login' %}" type="button" class="btn btn-sm btn-outline-secondary">Вход</a>
                    <a href="{% url 'users:register' %}" type="button" class="btn btn-sm btn-outline-secondary">Регистрация</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>
    {% block content %}
    {% endblock %}
    </div>
    </div>


</main>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Категории продуктов</h1>
        </div>
    </section>

<div class="row">
      {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ object.image }}"
                 alt="">
            <div class="card-body">
            <div class="text-center">

                    </div>
                <p class="card-text">{{ object.name }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:product_list' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Ассортимент</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary">Удалить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col">

        <a href="{% url 'catalog:list' %}" type="button"
           class="btn btn-outline-light">Back to list</a>

        <div class="card shadow-sm">
            <p class="text-center">Категория: {{ object.category }}</p></svg>
            <p class="text-center">{{ object.name }}</p></svg>
            <div class="text-center">
                <img src="{{ object.image | mymedia }}" class="rounded" alt="Card image cap">
            </div>
        </div>
    </div>
</div>
<div class="card-body">

    <p class="text-center">{{ object.description }}</p>
    <p class="text-center">Стоимость: {{ object.price }} рублей</p>
    <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">

            <a href="{% url 'catalog:category_list' %}" class="btn btn-sm btn-outline-secondary">Вернуться
                на главную</a>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">

                    <div class="btn-group">
                        <a href="{% url 'catalog:product_list' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">К ассортименту категории</a>
                    </div>
                    <div class="btn-group">
                        <div class="btn-group">
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">Добавление продукта</h2>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-secondary">Сохранить</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
<!--        {% if object.owner == request.user or user.is_superuser %}-->
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <div class="card-title">
                        {% if object.pk %}
                        <h2>Редактирование версии</h2>
                        {% else %}
                        <h2>Добавление версии</h2>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">
                    {{ formset.management_form}}
                    {% for form in formset.forms %}
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                    <form>
                        <button type="submit" name="save" class="btn btn-outline-secondary">Сохранить</button>
                        <span style="margin-left: 10px;"></span>
                        <input type="button" class="btn btn-outline-secondary" value="Назад"
                               onclick="history.back()">
                    </form>
                </div>
            </div>
        </div>
<!--        {% endif %}-->
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Каталог продуктов</h1>
    </div>
</section>
<!--{% if  user.is_superuser or user.is_active and perms.catalog.add_product  %}-->
<div class="col-12">
    <a href="{% url 'catalog:create_product' %}" type="button"
       class="btn btn-outline-secondary">Добавить продукт и версию</a>
</div>
<!--{% endif %}-->

<div class="row">
    {% for object in object_list %}
    {% if object.is_published or user.is_staff or user.is_superuser or object.owner == request.user %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ object.image }}"
                 alt="">
            <div class="card-body">
                <div class="text-center">
                    <img src="/media/{{ object.image }}" class="rounded" alt="preview" width="60%" height="200">
                </div>
                <p class="card-text">{{ object.name }}</p>
                <span class="text-muted">{{ object.owner|default:"Без автора" }}</span>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:detail_list' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Подробнее</a>
                        {% if object.owner == request.user or user.is_superuser or user.is_staff %}
                            <a href="{% url 'catalog:update_product' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Редактировать</a>
                        {% endif %}
                        {% if object.owner == request.user or user.is_superuser%}
                        <a href="{% url 'catalog:delete_product' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}